# Basic set up for npm

version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/account-component"
    schedule:
      interval: "weekly"
      day: "tuesday"
